// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bgjjvnkabtnpdushlcac.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJnamp2bmthYnRucGR1c2hsY2FjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI2NTUzODIsImV4cCI6MjA2ODIzMTM4Mn0.mHxwSL9PqqVVxDZSXSwHffokdJV9-n5F519DJpwXHhI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});